//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CvEntitiyProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_SKILS
    {
        public int ID { get; set; }
        public string SKILS { get; set; }
        public Nullable<int> DEGREE { get; set; }
    }
}
