//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CvEntitiyProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MYWORKS
    {
        public int ID { get; set; }
        public string ADDRESS { get; set; }
        public string IMAGE { get; set; }
        public string NOTE { get; set; }
    }
}
