//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CvEntitiyProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CvEntityEntities1 : DbContext
    {
        public CvEntityEntities1()
            : base("name=CvEntityEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_ABOUT> TBL_ABOUT { get; set; }
        public virtual DbSet<TBL_ADDRESS> TBL_ADDRESS { get; set; }
        public virtual DbSet<TBL_ADMIN> TBL_ADMIN { get; set; }
        public virtual DbSet<TBL_CERTIFICATES> TBL_CERTIFICATES { get; set; }
        public virtual DbSet<TBL_COMMUNICATION> TBL_COMMUNICATION { get; set; }
        public virtual DbSet<TBL_ICON> TBL_ICON { get; set; }
        public virtual DbSet<TBL_MYWORKS> TBL_MYWORKS { get; set; }
        public virtual DbSet<TBL_SKILS> TBL_SKILS { get; set; }
    }
}
