//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CvEntitiyProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CvEntityEntities : DbContext
    {
        public CvEntityEntities()
            : base("name=CvEntityEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_ABOUT> TBL_ABOUT { get; set; }
        public virtual DbSet<TBL_ADDRESS> TBL_ADDRESS { get; set; }
        public virtual DbSet<TBL_COMMUNICATİON> TBL_COMMUNICATİON { get; set; }
        public virtual DbSet<TBL_MYWORKS> TBL_MYWORKS { get; set; }
        public virtual DbSet<TBL_SKILS> TBL_SKILS { get; set; }
        public virtual DbSet<TBL_ADMİN> TBL_ADMİN { get; set; }
    }
}
