//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CvEntitiyProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ADDRESS
    {
        public byte ID { get; set; }
        public string TELEPHONE { get; set; }
        public string MAİL { get; set; }
        public string ADDRESS { get; set; }
        public string LOCASYON { get; set; }
    }
}
